INSERT INTO `BHP_BACK_OFFICE`.`CITY` (`CODE`,`DESC`,`STATE_ID`)
VALUES ("",'Narora',1662);

INSERT INTO `BHP_BACK_OFFICE`.`CITY` (`CODE`,`DESC`,`STATE_ID`)
VALUES ("",'Paschim Medinipur',1665);

DELETE FROM BHP_BACK_OFFICE.STATE WHERE ID IN ( 1642,1651,1652,1654,1664 );

SELECT ID FROM BHP_BACK_OFFICE.STATE WHERE CNTRY_ID = 101 AND `DESC` IN 
('Vaishali','Paschim Medinipur','Natwar','Narora','Kenmore');
