INSERT INTO `BHP_BACK_OFFICE`.`MST_TASK` (`TSK_DESC`, `TSK_KEY`, `TSK_OWNR_ROLE`) VALUES ('Reimburse Verification', 'REIMBURSE_VERIFICATION', 'HRM');
INSERT INTO `BHP_BACK_OFFICE`.`MST_TASK` (`TSK_DESC`, `TSK_KEY`) VALUES ('Reimburse Approval', 'REIMBURSE_APPR');
UPDATE `BHP_BACK_OFFICE`.`MST_TASK` SET `NXT_TSK_ID`='8' WHERE `ID`='7';
