INSERT INTO `BHP_BACK_OFFICE`.`MST_TASK` (`TSK_DESC`, `TSK_KEY`, `TSK_OWNR_ROLE`) VALUES ('Reimburse Verification', 'REIMBURSE_VERIFICATION', 'HRM');
INSERT INTO `BHP_BACK_OFFICE`.`MST_TASK` (`TSK_DESC`, `TSK_KEY`) VALUES ('Reimburse Approval', 'REIMBURSE_APPR');
UPDATE `BHP_BACK_OFFICE`.`MST_TASK` SET `NXT_TSK_ID`='8' WHERE `ID`='7';
UPDATE `BHP_BACK_OFFICE`.`MST_TASK` SET `NXT_TSK_ID`='9', `TSK_KEY`='REIMBURSE_FM_APPR', `TSK_OWNR_ROLE`='FM' WHERE `ID`='8';
INSERT INTO `BHP_BACK_OFFICE`.`MST_TASK` (`TSK_DESC`, `TSK_KEY`, `TSK_OWNR_ROLE`) VALUES ('Reimburse Approval', 'REIMBURSE_BU_APPR', 'BU');
UPDATE `BHP_BACK_OFFICE`.`MST_TASK` SET `TSK_DESC`='Reimburse Approval and Verification', `TSK_KEY`='REIMBURSE_HRM_APPR' WHERE `ID`='7';

